del /F /Q CREDENTIALS.md
del /F /Q DEPLOYMENT.md
del /F /Q HOW_TO_RUN.md
del /F /Q INSTALL_UI_ENHANCEMENTS.md
del /F /Q LINKS.md
del /F /Q LOGIN_FLOW.md
del /F /Q PROJECT_PROMPT.md
del /F /Q QUICK_START.md
del /F /Q README.md
del /F /Q RUN_APPLICATION.md
del /F /Q SETUP.md
del /F /Q TERMINAL_COMMANDS.md
del /F /Q TROUBLESHOOTING.md
del /F /Q UI_ENHANCEMENTS.md
del /F /Q QUICK_START.txt
del /F /Q setup-and-run.ps1
del /F /Q start-backend.ps1
del /F /Q start-frontend.ps1
